In [4]:
import numpy as np
import scipy.ndimage as scidi
import matplotlib.pyplot as plt
from PIL import Image
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)

In [2]:
### Problem 6


def makeMeAGrid(k:int,t:int,m:int,n:int,v:int,w:int,letter:str):
    name = "HW2Prob6" + letter+".txt"
    Array = np.zeros(((k*m+(m+1)*t),(k*n+(n+1)*t)))
    Array+= v
    rows = [t+p+l*(t+k) for l in range(m) for p in range(k)]
    cols = [t+p+l*(t+k) for l in range(n) for p in range(k)]
    for i in rows:
        for j in cols:
            Array[i,j] = w
    with open(name,'w') as f:
        for line in Array:
            f.write(str(line))
            f.write('\n')
    f.close()
    return Array

Ex = makeMeAGrid(2,1,1,5,9,1,"Example")


In [9]:
Ex = makeMeAGrid(2,1,1,5,9,1,"Example")
A = makeMeAGrid(1,2,2,2,3,0,"A")
B = makeMeAGrid(10,2,6,8,255,128,"B")
C = makeMeAGrid(4,4,2,10,255,0,"C")
D = makeMeAGrid(100,1,3,8,0,255,"D")


In [11]:
F = np.asarray([[5,2,0,1,8],[9,1,4,3,2],[3,4,0,5,1],[3,1,2,2,1]])
H = np.asarray([[0,1,0],[1,4,1],[0,1,0]])

In [14]:
print(scidi.correlate(F,H,mode = 'constant'))
print(scidi.convolve(F,H,mode = 'constant'))


H2 = scidi.convolve(H,H,mode = 'constant')
H3 = scidi.convolve(H,H2,mode = 'constant')
print(scidi.convolve(F,H3,mode = 'constant'))


[[31 14  7 15 35]
 [45 23 20 24 20]
 [28 21 15 26 12]
 [16 13 11 16  7]]
[[31 14  7 15 35]
 [45 23 20 24 20]
 [28 21 15 26 12]
 [16 13 11 16  7]]
[[1200  872  488  872 1136]
 [1656 1368  960 1224 1040]
 [1280 1160 1008 1112  680]
 [ 656  688  608  696  400]]


In [19]:

with Image.open(r"C:\Users\dchap\Documents\OneDrive\Pictures\Good_Photos\IMG_8300.jpg") as pic:
    numpypic = np.asarray(pic)
    pic.save("Original.jpg")
    S1 = scidi.gaussian_filter(np.uint8(numpypic),sigma = 1)
    Image.fromarray(S1).save("Sigma1.jpg")
    S2 = scidi.gaussian_filter(np.uint8(numpypic),sigma = 3)
    Image.fromarray(S2).save("Sigma3.jpg")
    S3 = scidi.gaussian_filter(np.uint8(numpypic),sigma = 5)
    Image.fromarray(S3).save("Sigma5.jpg")
    S4 = scidi.gaussian_filter(np.uint8(numpypic),sigma = 7)
    Image.fromarray(S4).save("Sigma7.jpg")
    S5 = scidi.gaussian_filter(np.uint8(numpypic),sigma = 9)
    Image.fromarray(S5).save("Sigma9.jpg")


TypeError: Cannot handle this data type: (1, 1, 3, 4), |u1