In [16]:
import numpy as np
from numpy.linalg import matrix_power

A = np.asarray([[4,2,3,7],[3,5,2,1],[1,9,4,2]])
B = np.asarray([[2,7,6],[1,3,2],[4,5,1]])

In [17]:

print(matrix_power((A@np.transpose(A)),5))

[[43656066711 37024251209 59416680210]
 [37024251209 31498508478 50577837358]
 [59416680210 50577837358 81222370620]]


In [18]:
print(matrix_power(np.transpose(A)@A,2))

[[ 3273  6717  3897  4506]
 [ 6717 17197  9079  8736]
 [ 3897  9079  4990  5223]
 [ 4506  8736  5223  6335]]


In [20]:
print(matrix_power(B@A-np.transpose((np.transpose(A)@B)),4))

LinAlgError: Last 2 dimensions of the array must be square